Use graphiql.css from imported module #180
enonic/app-guillotine pull request #181
Opened 2022-07-13 08:01 UTC by ashklianko

2022-07-13 09:24 UTC, alansemenov requested changes

2022-07-13 09:24 UTC, alansemenov commented on src/main/resources/assets/styles/main.less
> +@import "../../../../../node_modules/graphiql/graphiql.css";
`@import "graphiql/graphiql.css"` should be enough. Webpack resolves everything in `node_modules` without having to provide the entire path.

2022-07-13 11:07 UTC, ashklianko commented
Updated

2022-07-14 08:43 UTC, alansemenov approved these changes

2022-07-14 08:43 UTC, merged