Document Query DSL and Highlight #334
enonic/app-guillotine pull request #335
Opened 2023-01-13 14:43 UTC by anatol-sialitski

2023-01-16 15:33 UTC, rymsha approved these changes

2023-01-17 08:47 UTC, alansemenov commented on docs/api.adoc
> +|A query string to match field value(s). Support the set of operators.
```suggestion
|A query string to match field value(s). Supports the set of https://developer.enonic.com/docs/xp/next/storage/dsl#search_string_operators[operators].
```

2023-01-17 08:49 UTC, alansemenov commented on docs/api.adoc
> +|A query string to match field value(s). Support the set of operators.
```suggestion
|language: String!
|Content language that was used for stemming. List of https://developer.enonic.com/docs/xp/next/storage/indexing#languages[supported languages]
```

2023-01-17 08:50 UTC, alansemenov commented on docs/api.adoc
> +|A query string to match field value(s). Support the set of operators.
|query: String!
|A query string to match field value(s). Supports the set of https://developer.enonic.com/docs/xp/next/storage/dsl#search_string_operators[operators].

2023-01-17 08:54 UTC, alansemenov requested changes

2023-01-17 08:54 UTC, alansemenov commented on docs/api.adoc
> +|Name of a field to check on existence.
```suggestion
|Name of a field to check for existence.
```

2023-01-17 08:54 UTC, alansemenov commented on docs/api.adoc
> +|Name of a field to check on existence.
```suggestion
|Name of a field to sort by.
```

2023-01-17 13:29 UTC, alansemenov approved these changes

2023-03-23 09:10 UTC, merged